version: "3.2"
#name: media-stack
services:
  transmission:
    profiles: ["jellyfin", "plex"]
    container_name: transmission
    image: linuxserver/transmission:version-3.00-r8
    networks:
      - mynetwork
    # network_mode: service:vpn # Uncomment this line if vpn is enabled
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=phuong17889
      - PASS=S40l41th3

    ## Comment below ports if VPN is enabled.
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - tx-config:/config
      - tx-watch:/watch
      - /mnt/e/Downloads:/downloads
    restart: "unless-stopped"

  ## Default credentials - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  radarr:
    profiles: ["jellyfin", "plex"]
    container_name: radarr
    image: linuxserver/radarr:4.3.2
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - /mnt/e/Downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    profiles: ["jellyfin", "plex"]
    image: linuxserver/sonarr:develop-version-4.0.0.334
    container_name: sonarr
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - /mnt/e/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    profiles: ["jellyfin", "plex"]
    container_name: jackett
    image: linuxserver/jackett:0.20.2489
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jackett-config:/config
      - jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    profiles: ["jellyfin"]
    image: linuxserver/jellyfin:10.8.9
    container_name: jellyfin
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - /mnt/e/Downloads:/data
  # devices:
   #  - /dev/videoN:/dev/videoN # Mount GPU device
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped

  plex:
    profiles: ["plex"]
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    networks:
      - mynetwork
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400
      - 32469:32469
      - 1900:1900/udp
    volumes:
      - plex-config:/config
      - /mnt/e/Downloads/tvshows:/tv
      - /mnt/e/Downloads/movies:/movies
    restart: unless-stopped

volumes:
#  torrent-downloads:
  radarr-config:
  sonarr-config:
  jackett-config:
  jackett-blackhole:
  jellyfin-config:
  plex-config:
  tx-config:
  tx-watch:

networks:
  mynetwork:
    external: true
